### ISSUE TITLE
Comment crashes parser

### ISSUE THREAD

**Issue by acfsmith** [fktn-k/fkYAML#272] opened 2024-03-07 07:30 UTC
### Description

This YAML file crashes deserializer:

```yaml
test:
  # comment
  - item: 123
```

### Reproduction steps

```c++
std::ifstream ifs("test.yaml");
fkyaml::node root = fkyaml::node::deserialize(ifs);
```

### Expected vs. actual results

The YAML file is valid according to the YAML validator.  The parser shouldn't crash on it.

### Compiler and operating system

Linux, clang version 16.0.6

### Library version

0.3.1

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/fktn-k/fkYAML/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/fktn-k/fkYAML#how-to-execute-the-unit-tests).

**Comment by fktn-k** [comment] 2024-03-07 11:57
@acfsmith   
Thanks for your report! I'll take a look.

**Comment by fktn-k** [comment] 2024-03-09 12:06
@acfsmith   
I've fixed the crash in the PR #273.  
Can you confirm if the issue is resolved on your environment in the develop branch?

**Comment by acfsmith** [comment] 2024-03-11 04:20
I have checked the latest version.  It doesn't crash anymore.  Thank you very much!

**Comment by fktn-k** [comment] 2024-03-11 07:10
@acfsmith   
Thanks for your quick confirmation!  
I'll close this issue then.

**Closed** 2024-03-11 07:10 UTC
