### ISSUE TITLE
node.hpp(1351): Error C4800 : Implicit conversion from 'int' to bool. Possible information loss

### ISSUE THREAD

**Issue by tomwpid** [fktn-k/fkYAML#429] opened 2024-11-17 20:26 UTC
### Description

The following warning is generated when compiling with the node.hpp header included.

### Reproduction steps

Include node.hpp without the warning C4800 disabled.

### Expected vs. actual results

Expected: No warning should be generated.
Actual: Warning C4800 is generated.

### Minimal code example

```Shell
default:
            // alphabets and numbers are also allowed.
            return std::isalnum(c);
        }
```

### Error messages

```Shell
node.hpp(1351): Error C4800 : Implicit conversion from 'int' to bool. Possible information loss
```

### Compiler and operating system

Compiler: MSVC v143 - v14.38 - 17.8 OS: Windows

### Library version

0.3.14

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/fktn-k/fkYAML/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/fktn-k/fkYAML#how-to-execute-the-unit-tests).

**Comment by fktn-k** [comment] 2024-11-18 14:54
@tomwpid   
Thanks for filing this issue.  
The warning C4800 is not enabled with the compile option `/W4` and I didn't know the warning is raised.  
I could reproduce the warning by passing the compile option `/w44800` in when building the test suite.  
I'll resolve the warning soon (I'm working on it), but I'm not planning to pass the compile `/Wall` since it enables so many warnings which I wouldn't like to take care of...

**Comment by tomwpid** [comment] 2024-11-18 17:25
OK - thank you!

**Comment by fktn-k** [comment] 2024-11-19 02:13
@tomwpid   
The C4800 warning should be resolved by the PR #430.  
Could you confirm the fix with the develop HEAD?

**Comment by tomwpid** [comment] 2024-11-19 14:54
@fktn-k - Confirmed, PR https://github.com/fktn-k/fkYAML/pull/430 has fixed it.

**Comment by fktn-k** [comment] 2024-11-20 00:06
@tomwpid   
Thanks! I'll close this issue then.  
Feel free to reopen it if you find anything related but unresolved.

**Closed** 2024-11-20 00:07 UTC
